### ISSUE TITLE
How to enable client side metrics

### ISSUE THREAD

**Issue by ghost** [apakulov/kafka-graphite#8]
I was trying to use GraphiteReporter to get `kafka.consumer` metrics in Graphite. No chance so far.

My setup is that I implemented a JAVA projcect of a simple consumer. Put this properties in class path:

```
metric.reporters=org.apache.kafka.common.metrics.GraphiteReporter
kafka.graphite.metrics.prefix=test
kafka.metrics.polling.interval.secs=1
kafka.graphite.metrics.reporter.enabled=true
kafka.graphite.metrics.host=10.0.0.10
kafka.graphite.metrics.port=200
kafka.graphite.metrics.jvm.enabled=false
```

I'm not sure how to get these metrics. From my search, `kafka.consumer` metrics have to be provided by client.

**Comment by apakulov** [comment]
hi @irajguavus, did you solve the issue?
